[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
    'cp .env.example .env || true',
    'php artisan key:generate --force',
    'npm ci --include=dev',
    'npm run build'
]

[start]
cmd = 'php -S 0.0.0.0:${PORT:-8000} -t public'
